import type { WorkspaceRecord } from '@pi-workbench/contracts';

export const workspaceRecords: WorkspaceRecord[] = [
  {
    id: 'record-session-lifecycle',
    kind: 'experiment',
    title: 'Pi Session 生命周期实验',
    summary: '记录从资源加载、session 创建、turn 提交到事件收敛的可观测验证步骤。',
    status: 'active',
    tags: ['Pi', 'session', 'lifecycle'],
    updatedAt: '2026-08-02T09:00:00.000Z',
    payload: { owner: 'runtime-lab', checks: 8, passing: true },
  },
  {
    id: 'record-stream-inspector',
    kind: 'experiment',
    title: 'SSE Inspector 流式事件实验',
    summary: '验证 thinking、text、tool 和 done 事件在浏览器 Inspector 中的顺序与呈现。',
    status: 'active',
    tags: ['SSE', 'events', 'inspector'],
    updatedAt: '2026-08-02T09:15:00.000Z',
    payload: { owner: 'web-lab', checks: 11, passing: true },
  },
  {
    id: 'record-knowledge-retrieval',
    kind: 'runbook',
    title: 'Markdown Knowledge 检索运行手册',
    summary: '说明如何检查 OKF frontmatter、执行本地搜索、读取来源并记录检索延迟。',
    status: 'active',
    tags: ['knowledge', 'Markdown', 'OKF', 'search'],
    updatedAt: '2026-08-02T09:30:00.000Z',
    payload: { owner: 'knowledge-lab', checks: 6, passing: true },
  },
  {
    id: 'record-readonly-boundary',
    kind: 'decision',
    title: '只读能力边界决策',
    summary: '确认 Agent 只接收 read 与 search_knowledge 能力，模型输出不等于宿主授权。',
    status: 'active',
    tags: ['security', 'read-only', 'capability'],
    updatedAt: '2026-08-02T09:45:00.000Z',
    payload: { owner: 'platform', approved: true, sideEffects: false },
  },
  {
    id: 'record-local-fixture',
    kind: 'fixture',
    title: '本地数据查询夹具',
    summary: '用于验证本地 SQLite 查询、空结果、状态过滤和证据引用的最小数据集。',
    status: 'draft',
    tags: ['SQLite', 'fixture', 'query'],
    updatedAt: '2026-08-02T10:00:00.000Z',
    payload: { owner: 'data-lab', checks: 4, passing: false },
  },
];
